import pandas as pd
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader
from io import BytesIO
from datetime import datetime
import matplotlib.pyplot as plt

def analyze_csv(file):
    df = pd.read_csv(file)
    df.columns = df.columns.str.strip().str.lower()

    return {
        "total_equipment": len(df),
        "avg_flowrate": round(df["flowrate"].mean(), 2),
        "avg_pressure": round(df["pressure"].mean(), 2),
        "avg_temperature": round(df["temperature"].mean(), 2),
       "type_distribution": df["type"].value_counts().to_dict(),
        "table_data": df.to_dict(orient="records")
    }

def generate_dataset_pdf(dataset, analysis, chart_data=None):
    buffer = BytesIO()
    p = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4
    y = height - 50

    p.setFont("Helvetica-Bold", 18)
    p.drawString(50, y, "Dataset Analysis Report")
    y -= 40

    p.setFont("Helvetica", 11)
    p.drawString(50, y, f"Dataset ID: {dataset.id}")
    y -= 20
    p.drawString(50, y, f"Uploaded on: {dataset.uploaded_at.strftime('%d %b %Y')}")
    y -= 20
    p.drawString(50, y, f"Generated on: {datetime.now().strftime('%d %b %Y %H:%M')}")
    y -= 30

    p.setFont("Helvetica-Bold", 14)
    p.drawString(50, y, "Summary Statistics")
    y -= 25

    p.setFont("Helvetica", 11)
    for key, value in analysis.items():
        # Skip df/table_data if present
        if key in ["table_data", "df"]:
            continue
        p.drawString(60, y, f"{key.replace('_',' ').title()}: {value}")
        y -= 18

    
    if chart_data:
        for chart_name, values in chart_data.items():
            fig, ax = plt.subplots(figsize=(4,2))
            ax.bar(range(len(values)), values, color='skyblue')
            ax.set_title(chart_name)
            ax.set_ylabel(chart_name)
            plt.tight_layout()

            img_buffer = BytesIO()
            plt.savefig(img_buffer, format='PNG')
            plt.close(fig)
            img_buffer.seek(0)

            image = ImageReader(img_buffer)
            y -= 180
            if y < 100:
                p.showPage()
                y = height - 50
            p.drawImage(image, 50, y-150, width=500, height=150)
            y -= 170

    p.setFont("Helvetica-Oblique", 9)
    p.drawString(50, 20, f"Generated by {dataset.user.username} on {datetime.now().strftime('%d %b %Y')}")

    p.showPage()
    p.save()
    buffer.seek(0)
    return buffer
