# Generated by Django 6.0.1 on 2026-01-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentdataset',
            name='table_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
